interface Pasien {
    id: number;
    noRm: string;
    namaPasien: string;
    wargaNegara: string;
    nik: string;
    bpjs: string;
    noAsuransi: string;
    paspor: string;
    bahasa: string;
    noHp: string;
    tempatLahir: string;
    tanggalLahir: string;
    jenisKelamin: string;
    statusMenikah: string;
    agama: string;
    alamat: string;
    ibuKandung: string;
    provinsi: string;
    idProv: string;
    kota: string;
    idKota: string;
    kecamatan: string;
    idKecamatan: string;
    kelurahan: string;
    idKelurahan: string;
    rt: number;
    rw: number;
    kodePos: string;
    pendidikan: string;
    pekerjaan: string;
    alamatDomisili: string;
    provinsiDomisili: string;
    idProvDomisili: string;
    kotaDomisili: string;
    idKotaDomisili: string;
    kecamatanDomisili: string;
    idKecamatanDomisili: string;
    kelurahanDomisili: string;
    idKelurahanDomisili: string;
    rtDomisili: number;
    rwDomisili: number;
    kodePosDomisili: string;
    isAktif: boolean;
    createdAt: string;
    updatedAt: string;
    idFasyankes: string;
}

export interface EpisodePasien {
    id: number;
    episode: number;
    isAktif: boolean;
    createdAt: string;
    updatedAt: string;
    pasienId: number;
    idFasyankes: string;
    pasien: Pasien;
}